# Generated by Django 2.2.3 on 2019-07-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_teacher_titles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Schoolnews',
        ),
    ]
